"""
Demo music data for the AI Music Mood Matcher demonstration.

This module contains sample track data with realistic audio features
for demonstrating the mood analysis and music recommendation system.
"""

# Demo tracks with realistic audio features
TRACKS_DATA = [
    # ===== HAPPY/UPBEAT TRACKS =====
    {"name": "Feel Good Inc.", "artist": "Gorillaz", "album": "Demon Days", "danceability": 0.8,
        "energy": 0.9, "valence": 0.8, "tempo": 138, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "Happy", "artist": "Pharrell Williams", "album": "GIRL", "danceability": 0.9,
        "energy": 0.8, "valence": 0.95, "tempo": 160, "acousticness": 0.2, "mood_category": "happy"},
    {"name": "Good as Hell", "artist": "Lizzo", "album": "Cuz I Love You", "danceability": 0.85,
        "energy": 0.9, "valence": 0.9, "tempo": 140, "acousticness": 0.15, "mood_category": "happy"},
    {"name": "Can't Stop the Feeling!", "artist": "Justin Timberlake", "album": "Trolls Soundtrack", "danceability": 0.9,
        "energy": 0.85, "valence": 0.9, "tempo": 113, "acousticness": 0.15, "mood_category": "happy"},
    {"name": "Walking on Sunshine", "artist": "Katrina and the Waves", "album": "Walking on Sunshine", "danceability": 0.85,
        "energy": 0.9, "valence": 0.95, "tempo": 108, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "September", "artist": "Earth, Wind & Fire", "album": "The Best of Earth, Wind & Fire", "danceability": 0.9,
        "energy": 0.85, "valence": 0.9, "tempo": 126, "acousticness": 0.05, "mood_category": "happy"},
    {"name": "I Want It That Way", "artist": "Backstreet Boys", "album": "Millennium", "danceability": 0.7,
        "energy": 0.6, "valence": 0.8, "tempo": 100, "acousticness": 0.2, "mood_category": "happy"},
    {"name": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "album": "Uptown Special", "danceability": 0.95,
        "energy": 0.9, "valence": 0.9, "tempo": 115, "acousticness": 0.05, "mood_category": "happy"},
    {"name": "Good Vibrations", "artist": "The Beach Boys", "album": "Pet Sounds", "danceability": 0.75,
        "energy": 0.8, "valence": 0.85, "tempo": 119, "acousticness": 0.2, "mood_category": "happy"},
    {"name": "Mr. Blue Sky", "artist": "Electric Light Orchestra", "album": "Out of the Blue", "danceability": 0.8,
        "energy": 0.85, "valence": 0.95, "tempo": 180, "acousticness": 0.15, "mood_category": "happy"},
    {"name": "Dancing Queen", "artist": "ABBA", "album": "Arrival", "danceability": 0.9,
        "energy": 0.8, "valence": 0.9, "tempo": 101, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "I Got You (I Feel Good)", "artist": "James Brown", "album": "I Got You", "danceability": 0.85,
        "energy": 0.9, "valence": 0.9, "tempo": 140, "acousticness": 0.05, "mood_category": "happy"},
    {"name": "24K Magic", "artist": "Bruno Mars", "album": "24K Magic", "danceability": 0.9,
        "energy": 0.85, "valence": 0.85, "tempo": 106, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "Respect", "artist": "Aretha Franklin", "album": "I Never Loved a Man", "danceability": 0.8,
        "energy": 0.8, "valence": 0.85, "tempo": 115, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "Billie Jean", "artist": "Michael Jackson", "album": "Thriller", "danceability": 0.9,
        "energy": 0.8, "valence": 0.7, "tempo": 117, "acousticness": 0.05, "mood_category": "happy"},
    {"name": "Shake It Off", "artist": "Taylor Swift", "album": "1989", "danceability": 0.8,
        "energy": 0.8, "valence": 0.9, "tempo": 160, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "Celebration", "artist": "Kool & The Gang", "album": "Celebrate!", "danceability": 0.9,
        "energy": 0.85, "valence": 0.95, "tempo": 125, "acousticness": 0.05, "mood_category": "happy"},
    {"name": "Don't Worry Be Happy", "artist": "Bobby McFerrin", "album": "Simple Pleasures", "danceability": 0.75,
        "energy": 0.7, "valence": 0.95, "tempo": 69, "acousticness": 0.3, "mood_category": "happy"},
    {"name": "Roar", "artist": "Katy Perry", "album": "Prism", "danceability": 0.7,
        "energy": 0.8, "valence": 0.85, "tempo": 90, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "Best Day of My Life", "artist": "American Authors", "album": "Oh, What a Life", "danceability": 0.8,
        "energy": 0.85, "valence": 0.9, "tempo": 95, "acousticness": 0.15, "mood_category": "happy"},
    {"name": "Sugar", "artist": "Maroon 5", "album": "V", "danceability": 0.85,
        "energy": 0.8, "valence": 0.85, "tempo": 120, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "Count on Me", "artist": "Bruno Mars", "album": "Doo-Wops & Hooligans", "danceability": 0.7,
        "energy": 0.6, "valence": 0.9, "tempo": 124, "acousticness": 0.4, "mood_category": "happy"},
    {"name": "Three Little Birds", "artist": "Bob Marley", "album": "Exodus", "danceability": 0.8,
        "energy": 0.7, "valence": 0.9, "tempo": 76, "acousticness": 0.2, "mood_category": "happy"},
    {"name": "Lovely Day", "artist": "Bill Withers", "album": "Menagerie", "danceability": 0.7,
        "energy": 0.6, "valence": 0.9, "tempo": 110, "acousticness": 0.2, "mood_category": "happy"},
    {"name": "Here Comes the Sun", "artist": "The Beatles", "album": "Abbey Road", "danceability": 0.6,
        "energy": 0.6, "valence": 0.85, "tempo": 129, "acousticness": 0.3, "mood_category": "happy"},
    {"name": "Good Time", "artist": "Owl City & Carly Rae Jepsen", "album": "The Midsummer Station", "danceability": 0.8,
        "energy": 0.8, "valence": 0.9, "tempo": 125, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "I'm Yours", "artist": "Jason Mraz", "album": "We Sing. We Dance. We Steal Things.", "danceability": 0.7,
        "energy": 0.6, "valence": 0.85, "tempo": 153, "acousticness": 0.4, "mood_category": "happy"},
    {"name": "High Hopes", "artist": "Panic! At The Disco", "album": "Pray for the Wicked", "danceability": 0.65,
        "energy": 0.8, "valence": 0.8, "tempo": 82, "acousticness": 0.15, "mood_category": "happy"},
    {"name": "On Top of the World", "artist": "Imagine Dragons", "album": "Night Visions", "danceability": 0.7,
        "energy": 0.75, "valence": 0.85, "tempo": 90, "acousticness": 0.2, "mood_category": "happy"},
    {"name": "Sunflower", "artist": "Post Malone & Swae Lee", "album": "Spider-Man: Into the Spider-Verse", "danceability": 0.8,
        "energy": 0.7, "valence": 0.8, "tempo": 90, "acousticness": 0.2, "mood_category": "happy"},
    {"name": "Send Me on My Way", "artist": "Rusted Root", "album": "When I Woke", "danceability": 0.75,
        "energy": 0.8, "valence": 0.9, "tempo": 120, "acousticness": 0.3, "mood_category": "happy"},
    {"name": "I Will Survive", "artist": "Gloria Gaynor", "album": "Love Tracks", "danceability": 0.8,
        "energy": 0.8, "valence": 0.85, "tempo": 117, "acousticness": 0.1, "mood_category": "happy"},
    {"name": "Twist and Shout", "artist": "The Beatles", "album": "Please Please Me", "danceability": 0.85,
        "energy": 0.9, "valence": 0.9, "tempo": 124, "acousticness": 0.1, "mood_category": "happy"},

    # ===== SAD/MELANCHOLIC TRACKS =====
    {"name": "Someone Like You", "artist": "Adele", "album": "21", "danceability": 0.3,
        "energy": 0.2, "valence": 0.2, "tempo": 67, "acousticness": 0.8, "mood_category": "sad"},
    {"name": "Mad World", "artist": "Gary Jules", "album": "Donnie Darko Soundtrack", "danceability": 0.2,
        "energy": 0.1, "valence": 0.1, "tempo": 62, "acousticness": 0.9, "mood_category": "sad"},
    {"name": "Black", "artist": "Pearl Jam", "album": "Ten", "danceability": 0.3, "energy": 0.4,
        "valence": 0.2, "tempo": 75, "acousticness": 0.7, "mood_category": "sad"},
    {"name": "Hurt", "artist": "Johnny Cash", "album": "American IV: The Man Comes Around", "danceability": 0.2,
        "energy": 0.25, "valence": 0.15, "tempo": 86, "acousticness": 0.85, "mood_category": "sad"},
    {"name": "The Sound of Silence", "artist": "Simon and Garfunkel", "album": "Sounds of Silence", "danceability": 0.25,
        "energy": 0.2, "valence": 0.25, "tempo": 100, "acousticness": 0.8, "mood_category": "sad"},
    {"name": "Everybody Hurts", "artist": "R.E.M.", "album": "Automatic for the People", "danceability": 0.3,
        "energy": 0.3, "valence": 0.2, "tempo": 85, "acousticness": 0.7, "mood_category": "sad"},
    {"name": "Creep", "artist": "Radiohead", "album": "Pablo Honey", "danceability": 0.35,
        "energy": 0.4, "valence": 0.2, "tempo": 92, "acousticness": 0.4, "mood_category": "sad"},
    {"name": "Tears in Heaven", "artist": "Eric Clapton", "album": "Unplugged", "danceability": 0.3,
        "energy": 0.25, "valence": 0.3, "tempo": 80, "acousticness": 0.9, "mood_category": "sad"},
    {"name": "Hallelujah", "artist": "Jeff Buckley", "album": "Grace", "danceability": 0.25,
        "energy": 0.3, "valence": 0.25, "tempo": 62, "acousticness": 0.8, "mood_category": "sad"},
    {"name": "The Night We Met", "artist": "Lord Huron", "album": "Strange Trails", "danceability": 0.4,
        "energy": 0.3, "valence": 0.25, "tempo": 130, "acousticness": 0.75, "mood_category": "sad"},
    {"name": "Fix You", "artist": "Coldplay", "album": "X&Y", "danceability": 0.35,
        "energy": 0.4, "valence": 0.3, "tempo": 138, "acousticness": 0.6, "mood_category": "sad"},
    {"name": "Skinny Love", "artist": "Bon Iver", "album": "For Emma, Forever Ago", "danceability": 0.3,
        "energy": 0.2, "valence": 0.2, "tempo": 105, "acousticness": 0.85, "mood_category": "sad"},
    {"name": "Mad About You", "artist": "Sting", "album": "Ten Summoner's Tales", "danceability": 0.4,
        "energy": 0.35, "valence": 0.3, "tempo": 88, "acousticness": 0.6, "mood_category": "sad"},
    {"name": "Yesterday", "artist": "The Beatles", "album": "Help!", "danceability": 0.3,
        "energy": 0.2, "valence": 0.3, "tempo": 98, "acousticness": 0.9, "mood_category": "sad"},
    {"name": "Tears Don't Fall", "artist": "Bullet for My Valentine", "album": "The Poison", "danceability": 0.4,
        "energy": 0.7, "valence": 0.2, "tempo": 85, "acousticness": 0.1, "mood_category": "sad"},
    {"name": "Snuff", "artist": "Slipknot", "album": "All Hope Is Gone", "danceability": 0.3,
        "energy": 0.3, "valence": 0.15, "tempo": 70, "acousticness": 0.7, "mood_category": "sad"},
    {"name": "Cemetery Drive", "artist": "My Chemical Romance", "album": "Three Cheers for Sweet Revenge", "danceability": 0.4,
        "energy": 0.6, "valence": 0.2, "tempo": 120, "acousticness": 0.1, "mood_category": "sad"},
    {"name": "The Scientist", "artist": "Coldplay", "album": "A Rush of Blood to the Head", "danceability": 0.35,
        "energy": 0.4, "valence": 0.25, "tempo": 146, "acousticness": 0.6, "mood_category": "sad"},
    {"name": "Breathe Me", "artist": "Sia", "album": "Colour the Small One", "danceability": 0.35,
        "energy": 0.3, "valence": 0.2, "tempo": 95, "acousticness": 0.7, "mood_category": "sad"},
    {"name": "The Reason", "artist": "Hoobastank", "album": "The Reason", "danceability": 0.4,
        "energy": 0.5, "valence": 0.3, "tempo": 80, "acousticness": 0.4, "mood_category": "sad"},
    {"name": "How to Save a Life", "artist": "The Fray", "album": "How to Save a Life", "danceability": 0.4,
        "energy": 0.4, "valence": 0.3, "tempo": 123, "acousticness": 0.5, "mood_category": "sad"},
    {"name": "Mad World", "artist": "Tears for Fears", "album": "The Hurting", "danceability": 0.3,
        "energy": 0.3, "valence": 0.2, "tempo": 76, "acousticness": 0.4, "mood_category": "sad"},
    {"name": "Losing You", "artist": "Randy Newman", "album": "Toy Story 3", "danceability": 0.25,
        "energy": 0.2, "valence": 0.2, "tempo": 65, "acousticness": 0.8, "mood_category": "sad"},
    {"name": "The Man Who Sold the World", "artist": "David Bowie", "album": "The Man Who Sold the World", "danceability": 0.4,
        "energy": 0.6, "valence": 0.3, "tempo": 115, "acousticness": 0.2, "mood_category": "sad"},
    {"name": "Hurt", "artist": "Nine Inch Nails", "album": "The Downward Spiral", "danceability": 0.2,
        "energy": 0.3, "valence": 0.1, "tempo": 60, "acousticness": 0.4, "mood_category": "sad"},
    {"name": "Fake Plastic Trees", "artist": "Radiohead", "album": "The Bends", "danceability": 0.3,
        "energy": 0.4, "valence": 0.2, "tempo": 73, "acousticness": 0.5, "mood_category": "sad"},
    {"name": "Broken", "artist": "Seether ft. Amy Lee", "album": "Disclaimer II", "danceability": 0.3,
        "energy": 0.5, "valence": 0.15, "tempo": 85, "acousticness": 0.3, "mood_category": "sad"},
    {"name": "Heavy", "artist": "Linkin Park ft. Kiiara", "album": "One More Light", "danceability": 0.5,
        "energy": 0.4, "valence": 0.2, "tempo": 100, "acousticness": 0.4, "mood_category": "sad"},
    {"name": "Dust in the Wind", "artist": "Kansas", "album": "Point of Know Return", "danceability": 0.3,
        "energy": 0.2, "valence": 0.3, "tempo": 94, "acousticness": 0.9, "mood_category": "sad"},
    {"name": "Iris", "artist": "Goo Goo Dolls", "album": "Dizzy Up the Girl", "danceability": 0.4,
        "energy": 0.5, "valence": 0.3, "tempo": 119, "acousticness": 0.3, "mood_category": "sad"},
    {"name": "Angels", "artist": "Robbie Williams", "album": "Life thru a Lens", "danceability": 0.3,
        "energy": 0.3, "valence": 0.4, "tempo": 76, "acousticness": 0.6, "mood_category": "sad"},
    {"name": "Lightning Crashes", "artist": "Live", "album": "Throwing Copper", "danceability": 0.4,
        "energy": 0.6, "valence": 0.3, "tempo": 90, "acousticness": 0.2, "mood_category": "sad"},

    # ===== CALM/CHILL TRACKS =====
    {"name": "River", "artist": "Joni Mitchell", "album": "Blue", "danceability": 0.4,
        "energy": 0.3, "valence": 0.5, "tempo": 90, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "Holocene", "artist": "Bon Iver", "album": "Bon Iver, Bon Iver", "danceability": 0.3,
        "energy": 0.2, "valence": 0.4, "tempo": 68, "acousticness": 0.8, "mood_category": "calm"},
    {"name": "Aqueous Transmission", "artist": "Incubus", "album": "Morning View", "danceability": 0.2,
        "energy": 0.3, "valence": 0.5, "tempo": 80, "acousticness": 0.6, "mood_category": "calm"},
    {"name": "Weightless", "artist": "Marconi Union", "album": "Weightless", "danceability": 0.2,
        "energy": 0.15, "valence": 0.5, "tempo": 60, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "Clair de Lune", "artist": "Claude Debussy", "album": "Suite Bergamasque", "danceability": 0.1,
        "energy": 0.1, "valence": 0.6, "tempo": 72, "acousticness": 0.95, "mood_category": "calm"},
    {"name": "Gymnopédie No. 1", "artist": "Erik Satie", "album": "Gymnopédies", "danceability": 0.1,
        "energy": 0.1, "valence": 0.5, "tempo": 60, "acousticness": 0.95, "mood_category": "calm"},
    {"name": "Porcelain", "artist": "Moby", "album": "Play", "danceability": 0.4,
        "energy": 0.3, "valence": 0.6, "tempo": 90, "acousticness": 0.4, "mood_category": "calm"},
    {"name": "Teardrop", "artist": "Massive Attack", "album": "Mezzanine", "danceability": 0.3,
        "energy": 0.25, "valence": 0.4, "tempo": 73, "acousticness": 0.3, "mood_category": "calm"},
    {"name": "Mad Rush", "artist": "Philip Glass", "album": "Solo Piano", "danceability": 0.2,
        "energy": 0.2, "valence": 0.5, "tempo": 120, "acousticness": 0.95, "mood_category": "calm"},
    {"name": "On Earth as It Is in Heaven", "artist": "Ólafur Arnalds", "album": "...And They Have Escaped the Weight of Darkness", "danceability": 0.2,
        "energy": 0.2, "valence": 0.6, "tempo": 85, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "The Blue Notebooks", "artist": "Max Richter", "album": "The Blue Notebooks", "danceability": 0.15,
        "energy": 0.2, "valence": 0.5, "tempo": 65, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "Hotel California", "artist": "Eagles", "album": "Hotel California", "danceability": 0.4,
        "energy": 0.6, "valence": 0.5, "tempo": 75, "acousticness": 0.3, "mood_category": "calm"},
    {"name": "Imagine", "artist": "John Lennon", "album": "Imagine", "danceability": 0.4,
        "energy": 0.3, "valence": 0.6, "tempo": 76, "acousticness": 0.8, "mood_category": "calm"},
    {"name": "What's Going On", "artist": "Marvin Gaye", "album": "What's Going On", "danceability": 0.6,
        "energy": 0.5, "valence": 0.6, "tempo": 96, "acousticness": 0.3, "mood_category": "calm"},
    {"name": "Stairway to Heaven", "artist": "Led Zeppelin", "album": "Led Zeppelin IV", "danceability": 0.3,
        "energy": 0.6, "valence": 0.5, "tempo": 82, "acousticness": 0.4, "mood_category": "calm"},
    {"name": "Bridge Over Troubled Water", "artist": "Simon and Garfunkel", "album": "Bridge Over Troubled Water", "danceability": 0.3,
        "energy": 0.4, "valence": 0.6, "tempo": 85, "acousticness": 0.8, "mood_category": "calm"},
    {"name": "Spiegel im Spiegel", "artist": "Arvo Pärt", "album": "Tabula Rasa", "danceability": 0.1,
        "energy": 0.1, "valence": 0.5, "tempo": 60, "acousticness": 0.95, "mood_category": "calm"},
    {"name": "Metamorphosis", "artist": "Philip Glass", "album": "Solo Piano", "danceability": 0.2,
        "energy": 0.2, "valence": 0.5, "tempo": 80, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "Elegy for Dunkirk", "artist": "Dario Marianelli", "album": "Dunkirk", "danceability": 0.1,
        "energy": 0.3, "valence": 0.4, "tempo": 70, "acousticness": 0.8, "mood_category": "calm"},
    {"name": "Comptine d'un autre été", "artist": "Yann Tiersen", "album": "Amélie", "danceability": 0.3,
        "energy": 0.3, "valence": 0.6, "tempo": 88, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "Miserere Mei, Deus", "artist": "Gregorio Allegri", "album": "Classical Collection", "danceability": 0.1,
        "energy": 0.2, "valence": 0.5, "tempo": 60, "acousticness": 0.95, "mood_category": "calm"},
    {"name": "The Four Seasons: Spring", "artist": "Antonio Vivaldi", "album": "The Four Seasons", "danceability": 0.2,
        "energy": 0.4, "valence": 0.7, "tempo": 120, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "Ludovico Einaudi - Nuvole Bianche", "artist": "Ludovico Einaudi", "album": "Una Mattina", "danceability": 0.2,
        "energy": 0.2, "valence": 0.6, "tempo": 120, "acousticness": 0.95, "mood_category": "calm"},
    {"name": "Ambient 1: Music for Airports", "artist": "Brian Eno", "album": "Ambient 1: Music for Airports", "danceability": 0.1,
        "energy": 0.1, "valence": 0.5, "tempo": 50, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "Stars of the Lid - Requiem for Dying Mothers", "artist": "Stars of the Lid", "album": "The Tired Sounds of Stars of the Lid", "danceability": 0.1,
        "energy": 0.1, "valence": 0.4, "tempo": 40, "acousticness": 0.95, "mood_category": "calm"},
    {"name": "Hallelujah", "artist": "Leonard Cohen", "album": "Various Positions", "danceability": 0.3,
        "energy": 0.3, "valence": 0.5, "tempo": 96, "acousticness": 0.8, "mood_category": "calm"},
    {"name": "Mazzy Star - Fade Into You", "artist": "Mazzy Star", "album": "So Tonight That I Might See", "danceability": 0.3,
        "energy": 0.2, "valence": 0.4, "tempo": 82, "acousticness": 0.6, "mood_category": "calm"},
    {"name": "Radiohead - Daydreaming", "artist": "Radiohead", "album": "A Moon Shaped Pool", "danceability": 0.2,
        "energy": 0.2, "valence": 0.3, "tempo": 64, "acousticness": 0.7, "mood_category": "calm"},
    {"name": "Bon Iver - Re: Stacks", "artist": "Bon Iver", "album": "For Emma, Forever Ago", "danceability": 0.2,
        "energy": 0.2, "valence": 0.4, "tempo": 70, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "Iron & Wine - Boy with a Coin", "artist": "Iron & Wine", "album": "The Shepherd's Dog", "danceability": 0.4,
        "energy": 0.3, "valence": 0.5, "tempo": 90, "acousticness": 0.7, "mood_category": "calm"},
    {"name": "Nick Drake - River Man", "artist": "Nick Drake", "album": "Five Leaves Left", "danceability": 0.2,
        "energy": 0.2, "valence": 0.4, "tempo": 65, "acousticness": 0.9, "mood_category": "calm"},
    {"name": "Fleet Foxes - White Winter Hymnal", "artist": "Fleet Foxes", "album": "Fleet Foxes", "danceability": 0.4,
        "energy": 0.4, "valence": 0.6, "tempo": 150, "acousticness": 0.6, "mood_category": "calm"},
    {"name": "Sigur Rós - Hoppípolla", "artist": "Sigur Rós", "album": "Takk...", "danceability": 0.3,
        "energy": 0.4, "valence": 0.7, "tempo": 140, "acousticness": 0.3, "mood_category": "calm"},
    {"name": "Explosions in the Sky - Your Hand in Mine", "artist": "Explosions in the Sky", "album": "The Earth Is Not a Cold Dead Place", "danceability": 0.2,
        "energy": 0.4, "valence": 0.6, "tempo": 85, "acousticness": 0.3, "mood_category": "calm"},
    {"name": "Godspeed You! Black Emperor - Storm", "artist": "Godspeed You! Black Emperor", "album": "Lift Your Skinny Fists Like Antennas to Heaven", "danceability": 0.1,
        "energy": 0.3, "valence": 0.4, "tempo": 60, "acousticness": 0.4, "mood_category": "calm"},

    # ===== ENERGETIC/WORKOUT TRACKS =====
    {"name": "Till I Collapse", "artist": "Eminem", "album": "The Eminem Show", "danceability": 0.7,
        "energy": 0.95, "valence": 0.6, "tempo": 85, "acousticness": 0.05, "mood_category": "energetic"},
    {"name": "Pump It", "artist": "Black Eyed Peas", "album": "Monkey Business", "danceability": 0.9,
        "energy": 0.9, "valence": 0.8, "tempo": 124, "acousticness": 0.1, "mood_category": "energetic"},
    {"name": "Stronger", "artist": "Kanye West", "album": "Graduation", "danceability": 0.8,
        "energy": 0.85, "valence": 0.7, "tempo": 104, "acousticness": 0.1, "mood_category": "energetic"},
    {"name": "Break Stuff", "artist": "Limp Bizkit", "album": "Significant Other", "danceability": 0.6,
        "energy": 0.95, "valence": 0.2, "tempo": 95, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Bodies", "artist": "Drowning Pool", "album": "Sinner", "danceability": 0.5, "energy": 0.98,
        "valence": 0.15, "tempo": 152, "acousticness": 0.01, "mood_category": "energetic"},
    {"name": "Killing in the Name", "artist": "Rage Against the Machine", "album": "Rage Against the Machine",
        "danceability": 0.65, "energy": 0.97, "valence": 0.25, "tempo": 85, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Thunder", "artist": "Imagine Dragons", "album": "Evolve", "danceability": 0.75,
        "energy": 0.85, "valence": 0.7, "tempo": 168, "acousticness": 0.1, "mood_category": "energetic"},
    {"name": "Centuries", "artist": "Fall Out Boy", "album": "American Beauty/American Psycho", "danceability": 0.7,
        "energy": 0.9, "valence": 0.6, "tempo": 90, "acousticness": 0.05, "mood_category": "energetic"},
    {"name": "Radioactive", "artist": "Imagine Dragons", "album": "Night Visions", "danceability": 0.6,
        "energy": 0.85, "valence": 0.6, "tempo": 136, "acousticness": 0.1, "mood_category": "energetic"},
    {"name": "Eye of the Tiger", "artist": "Survivor", "album": "Eye of the Tiger", "danceability": 0.7,
        "energy": 0.9, "valence": 0.8, "tempo": 109, "acousticness": 0.05, "mood_category": "energetic"},
    {"name": "We Will Rock You", "artist": "Queen", "album": "News of the World", "danceability": 0.6,
        "energy": 0.85, "valence": 0.8, "tempo": 114, "acousticness": 0.1, "mood_category": "energetic"},
    {"name": "Don't Stop Me Now", "artist": "Queen", "album": "Jazz", "danceability": 0.75,
        "energy": 0.9, "valence": 0.95, "tempo": 156, "acousticness": 0.05, "mood_category": "energetic"},
    {"name": "Believer", "artist": "Imagine Dragons", "album": "Evolve", "danceability": 0.65,
        "energy": 0.9, "valence": 0.6, "tempo": 125, "acousticness": 0.1, "mood_category": "energetic"},
    {"name": "Can't Hold Us", "artist": "Macklemore & Ryan Lewis", "album": "The Heist", "danceability": 0.8,
        "energy": 0.95, "valence": 0.8, "tempo": 146, "acousticness": 0.05, "mood_category": "energetic"},
    {"name": "Titanium", "artist": "David Guetta ft. Sia", "album": "Nothing but the Beat", "danceability": 0.85,
        "energy": 0.9, "valence": 0.7, "tempo": 126, "acousticness": 0.05, "mood_category": "energetic"},
    {"name": "Bangarang", "artist": "Skrillex", "album": "Bangarang", "danceability": 0.8,
        "energy": 0.95, "valence": 0.7, "tempo": 110, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Lose Yourself", "artist": "Eminem", "album": "8 Mile Soundtrack", "danceability": 0.7,
        "energy": 0.9, "valence": 0.65, "tempo": 86, "acousticness": 0.05, "mood_category": "energetic"},
    {"name": "Welcome to the Jungle", "artist": "Guns N' Roses", "album": "Appetite for Destruction", "danceability": 0.6,
        "energy": 0.95, "valence": 0.6, "tempo": 125, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Bohemian Rhapsody", "artist": "Queen", "album": "A Night at the Opera", "danceability": 0.5,
        "energy": 0.7, "valence": 0.6, "tempo": 72, "acousticness": 0.2, "mood_category": "energetic"},
    {"name": "Sweet Child O' Mine", "artist": "Guns N' Roses", "album": "Appetite for Destruction", "danceability": 0.6,
        "energy": 0.9, "valence": 0.7, "tempo": 125, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Like a Rolling Stone", "artist": "Bob Dylan", "album": "Highway 61 Revisited", "danceability": 0.5,
        "energy": 0.7, "valence": 0.6, "tempo": 130, "acousticness": 0.2, "mood_category": "energetic"},
    {"name": "Purple Haze", "artist": "Jimi Hendrix", "album": "Are You Experienced", "danceability": 0.6,
        "energy": 0.9, "valence": 0.7, "tempo": 110, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Thunderstruck", "artist": "AC/DC", "album": "The Razors Edge", "danceability": 0.6,
        "energy": 0.95, "valence": 0.8, "tempo": 133, "acousticness": 0.01, "mood_category": "energetic"},
    {"name": "Back in Black", "artist": "AC/DC", "album": "Back in Black", "danceability": 0.7,
        "energy": 0.9, "valence": 0.7, "tempo": 93, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Highway to Hell", "artist": "AC/DC", "album": "Highway to Hell", "danceability": 0.7,
        "energy": 0.9, "valence": 0.8, "tempo": 114, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Crazy Train", "artist": "Ozzy Osbourne", "album": "Blizzard of Ozz", "danceability": 0.6,
        "energy": 0.95, "valence": 0.7, "tempo": 138, "acousticness": 0.01, "mood_category": "energetic"},
    {"name": "Living After Midnight", "artist": "Judas Priest", "album": "British Steel", "danceability": 0.7,
        "energy": 0.9, "valence": 0.8, "tempo": 130, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Number of the Beast", "artist": "Iron Maiden", "album": "The Number of the Beast", "danceability": 0.5,
        "energy": 0.95, "valence": 0.6, "tempo": 198, "acousticness": 0.01, "mood_category": "energetic"},
    {"name": "Master of Puppets", "artist": "Metallica", "album": "Master of Puppets", "danceability": 0.4,
        "energy": 0.98, "valence": 0.5, "tempo": 212, "acousticness": 0.01, "mood_category": "energetic"},
    {"name": "Enter Sandman", "artist": "Metallica", "album": "Metallica", "danceability": 0.5,
        "energy": 0.9, "valence": 0.5, "tempo": 123, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Paranoid", "artist": "Black Sabbath", "album": "Paranoid", "danceability": 0.6,
        "energy": 0.9, "valence": 0.6, "tempo": 164, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Ace of Spades", "artist": "Motörhead", "album": "Ace of Spades", "danceability": 0.6,
        "energy": 0.95, "valence": 0.7, "tempo": 138, "acousticness": 0.01, "mood_category": "energetic"},
    {"name": "Run to the Hills", "artist": "Iron Maiden", "album": "The Number of the Beast", "danceability": 0.5,
        "energy": 0.9, "valence": 0.7, "tempo": 184, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Smells Like Teen Spirit", "artist": "Nirvana", "album": "Nevermind", "danceability": 0.6,
        "energy": 0.9, "valence": 0.6, "tempo": 117, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Bulls on Parade", "artist": "Rage Against the Machine", "album": "Evil Empire", "danceability": 0.7,
        "energy": 0.95, "valence": 0.6, "tempo": 85, "acousticness": 0.01, "mood_category": "energetic"},
    {"name": "B.Y.O.B.", "artist": "System of a Down", "album": "Mezmerize", "danceability": 0.6,
        "energy": 0.95, "valence": 0.5, "tempo": 158, "acousticness": 0.01, "mood_category": "energetic"},
    {"name": "Chop Suey!", "artist": "System of a Down", "album": "Toxicity", "danceability": 0.5,
        "energy": 0.9, "valence": 0.4, "tempo": 127, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "One Step Closer", "artist": "Linkin Park", "album": "Hybrid Theory", "danceability": 0.6,
        "energy": 0.9, "valence": 0.5, "tempo": 96, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "In the End", "artist": "Linkin Park", "album": "Hybrid Theory", "danceability": 0.6,
        "energy": 0.8, "valence": 0.5, "tempo": 105, "acousticness": 0.05, "mood_category": "energetic"},
    {"name": "Freak on a Leash", "artist": "Korn", "album": "Follow the Leader", "danceability": 0.6,
        "energy": 0.9, "valence": 0.4, "tempo": 135, "acousticness": 0.02, "mood_category": "energetic"},
    {"name": "Down with the Sickness", "artist": "Disturbed", "album": "The Sickness", "danceability": 0.5,
        "energy": 0.95, "valence": 0.4, "tempo": 96, "acousticness": 0.01, "mood_category": "energetic"},

    # ===== ROMANTIC TRACKS =====
    {"name": "At Last", "artist": "Etta James", "album": "At Last!", "danceability": 0.5,
        "energy": 0.4, "valence": 0.7, "tempo": 75, "acousticness": 0.4, "mood_category": "romantic"},
    {"name": "Perfect", "artist": "Ed Sheeran", "album": "÷", "danceability": 0.6, "energy": 0.4,
        "valence": 0.8, "tempo": 95, "acousticness": 0.6, "mood_category": "romantic"},
    {"name": "Make You Feel My Love", "artist": "Adele", "album": "19", "danceability": 0.3,
        "energy": 0.3, "valence": 0.6, "tempo": 72, "acousticness": 0.8, "mood_category": "romantic"},
    {"name": "All of Me", "artist": "John Legend", "album": "Love in the Future", "danceability": 0.55,
        "energy": 0.35, "valence": 0.75, "tempo": 120, "acousticness": 0.65, "mood_category": "romantic"},
    {"name": "Thinking Out Loud", "artist": "Ed Sheeran", "album": "x", "danceability": 0.5,
        "energy": 0.4, "valence": 0.8, "tempo": 79, "acousticness": 0.7, "mood_category": "romantic"},
    {"name": "Unchained Melody", "artist": "The Righteous Brothers", "album": "Just Once in My Life", "danceability": 0.4,
        "energy": 0.4, "valence": 0.75, "tempo": 75, "acousticness": 0.6, "mood_category": "romantic"},
    {"name": "The Way You Look Tonight", "artist": "Frank Sinatra", "album": "Songs for Swingin' Lovers!", "danceability": 0.6,
        "energy": 0.5, "valence": 0.8, "tempo": 120, "acousticness": 0.3, "mood_category": "romantic"},
    {"name": "Can't Help Myself", "artist": "Four Tops", "album": "Four Tops Second Album", "danceability": 0.8,
        "energy": 0.7, "valence": 0.85, "tempo": 124, "acousticness": 0.1, "mood_category": "romantic"},
    {"name": "Stand by Me", "artist": "Ben E. King", "album": "Don't Play That Song!", "danceability": 0.6,
        "energy": 0.5, "valence": 0.8, "tempo": 118, "acousticness": 0.4, "mood_category": "romantic"},
    {"name": "Let's Stay Together", "artist": "Al Green", "album": "Let's Stay Together", "danceability": 0.7,
        "energy": 0.6, "valence": 0.8, "tempo": 115, "acousticness": 0.2, "mood_category": "romantic"},
    {"name": "La Vie En Rose", "artist": "Édith Piaf", "album": "The Complete Édith Piaf", "danceability": 0.5,
        "energy": 0.4, "valence": 0.8, "tempo": 90, "acousticness": 0.7, "mood_category": "romantic"},
    {"name": "Moon River", "artist": "Audrey Hepburn", "album": "Breakfast at Tiffany's", "danceability": 0.3,
        "energy": 0.3, "valence": 0.7, "tempo": 72, "acousticness": 0.8, "mood_category": "romantic"},
    {"name": "The Way We Were", "artist": "Barbra Streisand", "album": "The Way We Were", "danceability": 0.4,
        "energy": 0.4, "valence": 0.7, "tempo": 85, "acousticness": 0.6, "mood_category": "romantic"},
    {"name": "Wonderful Tonight", "artist": "Eric Clapton", "album": "Slowhand", "danceability": 0.5,
        "energy": 0.4, "valence": 0.8, "tempo": 95, "acousticness": 0.5, "mood_category": "romantic"},
    {"name": "Something", "artist": "The Beatles", "album": "Abbey Road", "danceability": 0.5,
        "energy": 0.4, "valence": 0.8, "tempo": 66, "acousticness": 0.4, "mood_category": "romantic"},
    {"name": "Just the Way You Are", "artist": "Billy Joel", "album": "The Stranger", "danceability": 0.6,
        "energy": 0.5, "valence": 0.8, "tempo": 120, "acousticness": 0.3, "mood_category": "romantic"},
    {"name": "Your Song", "artist": "Elton John", "album": "Elton John", "danceability": 0.5,
        "energy": 0.4, "valence": 0.8, "tempo": 133, "acousticness": 0.6, "mood_category": "romantic"},
    {"name": "When a Man Loves a Woman", "artist": "Percy Sledge", "album": "When a Man Loves a Woman", "danceability": 0.4,
        "energy": 0.5, "valence": 0.8, "tempo": 66, "acousticness": 0.4, "mood_category": "romantic"},
    {"name": "L-O-V-E", "artist": "Nat King Cole", "album": "L-O-V-E", "danceability": 0.6,
        "energy": 0.5, "valence": 0.9, "tempo": 120, "acousticness": 0.3, "mood_category": "romantic"},
    {"name": "The Very Thought of You", "artist": "Billie Holiday", "album": "Lady Day", "danceability": 0.4,
        "energy": 0.3, "valence": 0.8, "tempo": 80, "acousticness": 0.6, "mood_category": "romantic"},
    {"name": "Fly Me to the Moon", "artist": "Frank Sinatra", "album": "It Might as Well Be Swing", "danceability": 0.7,
        "energy": 0.5, "valence": 0.8, "tempo": 115, "acousticness": 0.2, "mood_category": "romantic"},
    {"name": "Isn't She Lovely", "artist": "Stevie Wonder", "album": "Songs in the Key of Life", "danceability": 0.8,
        "energy": 0.7, "valence": 0.9, "tempo": 110, "acousticness": 0.2, "mood_category": "romantic"},
    {"name": "Best Part", "artist": "Daniel Caesar ft. H.E.R.", "album": "Freudian", "danceability": 0.6,
        "energy": 0.4, "valence": 0.8, "tempo": 90, "acousticness": 0.5, "mood_category": "romantic"},
    {"name": "Golden", "artist": "Jill Scott", "album": "Who Is Jill Scott?", "danceability": 0.7,
        "energy": 0.5, "valence": 0.8, "tempo": 95, "acousticness": 0.3, "mood_category": "romantic"},
    {"name": "Adorn", "artist": "Miguel", "album": "Kaleidoscope Dream", "danceability": 0.8,
        "energy": 0.6, "valence": 0.8, "tempo": 85, "acousticness": 0.2, "mood_category": "romantic"},
    {"name": "Come Through and Chill", "artist": "Miguel ft. J. Cole", "album": "War & Leisure", "danceability": 0.7,
        "energy": 0.5, "valence": 0.7, "tempo": 80, "acousticness": 0.3, "mood_category": "romantic"},
    {"name": "Stay With Me", "artist": "Sam Smith", "album": "In the Lonely Hour", "danceability": 0.4,
        "energy": 0.4, "valence": 0.6, "tempo": 84, "acousticness": 0.6, "mood_category": "romantic"},
    {"name": "Say You Won't Let Go", "artist": "James Arthur", "album": "Back from the Edge", "danceability": 0.5,
        "energy": 0.4, "valence": 0.7, "tempo": 110, "acousticness": 0.7, "mood_category": "romantic"},
    {"name": "A Thousand Years", "artist": "Christina Perri", "album": "The Twilight Saga: Breaking Dawn", "danceability": 0.4,
        "energy": 0.3, "valence": 0.8, "tempo": 108, "acousticness": 0.8, "mood_category": "romantic"},
    {"name": "Marry Me", "artist": "Train", "album": "Save Me, San Francisco", "danceability": 0.5,
        "energy": 0.4, "valence": 0.8, "tempo": 120, "acousticness": 0.6, "mood_category": "romantic"},
    {"name": "Better Days", "artist": "OneRepublic", "album": "Human", "danceability": 0.6,
        "energy": 0.5, "valence": 0.7, "tempo": 95, "acousticness": 0.4, "mood_category": "romantic"},
    {"name": "Photograph", "artist": "Ed Sheeran", "album": "x", "danceability": 0.5,
        "energy": 0.4, "valence": 0.7, "tempo": 108, "acousticness": 0.7, "mood_category": "romantic"},
]
